import "./globals.css";

export const metadata = {
  title: "Expense Tracker App",
  description: "Generated by Ali Mahmoud",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{fontFamily:'inter'}}>
        {children}
      </body>
    </html>
  );
}
